runtime: nodejs14
env: standard

service: backtura

env_variables:
  DB_USER: $DB_USER
  DB_PWD: $DB_PWD
  DB_NAME: $DB_NAME
  DB_SOCKET: $DB_SOCKET
  API_KEY: $API_KEY

handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301
